### ISSUE TITLE
Can't see "Makefile way" easily

### ISSUE THREAD

**Issue by postoroniy** [SpinalHDL/SpinalDoc#22]
here description how to run make https://spinalhdl.github.io/SpinalDoc/spinal_getting_started/#makeWay
but I think better to say
"you  should checkout this repo and this _branch_ makefile"
instead of pointing to master branch which dedicated to sbt way
or even better add console commands in description to do so:
1) git clone https://github.com/SpinalHDL/SpinalBaseProject.git
2) cd SpinalBaseProjec
3) git checkout makefile
4) make run

**Comment by Dolu1990** [comment]
Hi,
You are right, it's now fixed, and more friendly ^^
Thanks for report !
