### ISSUE TITLE
Sfix weird range

### ISSUE THREAD

**Issue by postoroniy** [SpinalHDL/SpinalDoc#35]
https://spinalhdl.github.io/SpinalDoc/spinal/core/types/Fix#signed-fixed-point

resolution as 2^resolution 
max as 2^peak-2^resolution 
min as 0  <- WHY?

**Comment by Dolu1990** [comment]
Hoo that's a mistake, copy pasted from UFix, should be  -2^peak

**Comment by Dolu1990** [comment]
Fixed, sorry for the delay :/
