### ISSUE TITLE
Rawgit is closing down

### ISSUE THREAD

**Issue by wifasoi** [SpinalHDL/SpinalDoc#37]
Rawgit is closing down, so all links must use another CDN for serving files:
you can read about it here: https://rawgit.com/

**Comment by Dolu1990** [comment]
Damned, noooooooo XD
Any way, how is going the readTheDoc port ?
As a plan, we can put the readTheDoc port as the default website, and then i can port the rawGit stuff ?

**Comment by wifasoi** [comment]
The rawgit stuff is not a big deal (i think there are only 10 link that use it).
for the readTheDoc port: is all/almost done (the mayor thing is to change some table dimension..).
For where put the documentation:
we have the option to host the documentation on the readthedoc site, or via github page (or both).
I'll open another issue for discussing this
