### ISSUE TITLE
Sphinx port

### ISSUE THREAD

**Issue by wifasoi** [SpinalHDL/SpinalDoc#38]
I'm porting the documentation to use Sphinx instead of Jekyll.
This have some major advantages, like automatic pdf generation, possibility to host it on the readthedoc site (and update the documentation automatically, every release for example. Maintain the history of the documentation ecc..), and all the benefit restructured-text bring to the table.

you can check it out here: https://wifasoi.github.io/SpinalDoc-RTD/html/index.html

when the port is complete I can land you the repo, or create a massive PR for this one.

there are soe thing to do before I deem this port complete, like:
- [x] fix table column width

[this issue is related to #37]

**Comment by Dolu1990** [comment]
Great :D
I'm ok for the massive PR, then i will add a git tag to keep a good marker.
Let's me know if you need help :)

**Comment by Dolu1990** [comment]
Thanks ^.^ https://github.com/SpinalHDL/SpinalDoc-RTD
