### ISSUE TITLE
there is a mistake:  x(hi,lo)  Read bitfield, hi : Int, lo : Int  T(hi-lo+1 bits)

### ISSUE THREAD

**Issue by ArcheyChen** [SpinalHDL/SpinalDoc#40]
at:
https://spinalhdl.github.io/SpinalDoc-RTD/SpinalHDL/Developers%20area/types.html
"

x(hi,lo) | Read bitfield, hi : Int, lo : Int | T(hi-lo+1 bits)
-- | -- | --

"
it doesn't work any more

**Comment by Dolu1990** [comment]
Hooo right, that was done on purpose to only leave more explicit syntaxes, should be x(hi downto lo)

**Comment by Dolu1990** [comment]
Fixed in the doc
