### ISSUE TITLE
Spelling error. 

### ISSUE THREAD

**Issue by EETRAA** [SpinalHDL/SpinalDoc#42]
On this page：[Link here](https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/Structuring/parametrization.html#elaboration-time-parameters), in the first code box, misspelt the word "case". 

> **csae** class MyBus(width : Int) extends Bundle{
  val mySignal = UInt(width bits)
}

**Comment by wifasoi** [comment]
wrong repo, but anyway I'm fixing it.. thanks for the heads up.
(No need to open another issue, and i'm closing this one)

**Comment by wifasoi** [comment]
Fixed in [spinalhdl.github.io/spinaldoc-rtd/](https://spinalhdl.github.io/SpinalDoc-RTD/) (the correct repo for the doc)

**Comment by EETRAA** [comment]
Thanks. :smile_cat:
